force-app/main/default/objects/Field_Change_Archive__b/Field_Change_Archive__b.object-meta.xml
<CustomObject>
    <label>Field_Change_Archive</label>
    <pluralLabel>Field_Change_Archive</pluralLabel>
</CustomObject>

force-app/main/default/objects/Field_Change_Archive__b/fields/ChangedBy__c.field-meta.xml
<CustomField>
    <fullName>ChangedBy__c</fullName>
    <label>ChangedBy</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Field_Change_Archive</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Field_Change_Archive__b/fields/ChangedOn__c.field-meta.xml
<CustomField>
    <fullName>ChangedOn__c</fullName>
    <label>ChangedOn</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Field_Change_Archive__b/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <label>FieldName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Change_Archive__b/fields/NewValue__c.field-meta.xml
<CustomField>
    <fullName>NewValue__c</fullName>
    <label>NewValue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Change_Archive__b/fields/OldValue__c.field-meta.xml
<CustomField>
    <fullName>OldValue__c</fullName>
    <label>OldValue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Change_Archive__b/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>ParentId</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FieldHistoryViewerController.cls
// Apex Controller: FieldHistoryViewerController.cls
public with sharing class FieldHistoryViewerController {

    @AuraEnabled(cacheable=true)
    public static List<Field_Change_Archive__b> getFieldChangeHistory(String parentId) {
        if (String.isBlank(parentId)) {
            throw new AuraHandledException('ParentId is required');
        }

        DateTime changedBefore = DateTime.now();

        List<Field_Change_Archive__b> results = [
            SELECT FieldName__c, OldValue__c, NewValue__c, ChangedBy__c, ChangedBy__r.Name, ChangedOn__c
FROM Field_Change_Archive__b
WHERE ParentId__c = :parentId
AND ChangedOn__c <= :changedBefore
ORDER BY ParentId__c ASC,  ChangedOn__c DESC
LIMIT 100

        ];

        return results;
    }
}